# example netlify.toml
[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/"
  to = "/en" 
  force = true # ensure to always redirect